# -*- coding: utf-8 -*-
"""UgurbeyDemirdelenMidterm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/165SY1uDWbHA_oiBFr0S4WB-S3AG6k5a7

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on Drive.
ex: atay_ilgun_MIDTERM.ipynb

Describe what ML is in 50 words.
"""

# It is a sub-field of computer science that depends on the computaised patternisation. 
# ML stands for Machine Learning, it stands exactly for its given name: With machine learning computers develop an act of learning just like we humans do. The computers learn via pattern recognition systems
# and algorithms that forms within the surrounded patterns that computer manages to detect. It is the fundamental necessity for the AI.

"""Give 3 examples of ML in practical use in todays world - also, meditate on how it is being utilised as well."""

# 1) It can be a great source of identifying our possible liked topics in any kind of medium. Be it music or the art.
# 2) It can aid us in fixing our 'humanly' mistakes. Such as when writing or even coding!
# 3) Heck! It can help in our designs. With its immense arsenal of data library, it can help us design what we wish just by acquiring our given information. Also the randomisation is great for getting an easy awe of inspiration

# The ML is utilised in many media application, tools; almost at anythying today!  They are graetly utilised in surveillance, tracking, gathering data of us, the humans. These data help us in specific fields.
# Be it law enforcement, or having our wacky Spotify Top 10 Playlist that all fit to our taste. How nice, yet it may spooks us time to time.

"""In ML terminology what is an 'example', 'feature', 'label' and 'feature vector'?"""

# Example is the one line of data inputs within a code list. It defines the all trained attributes for the computer.
# Feature is a one colum of data inputs within a code list. Such as, weight, age etc. of an item.
# Label is a column of trained data which is the item. An item that has its feature at a given list.
# Feature vector is a column or a line of numerical data values within a code list. They can be integers (0-9) or float values (10+).

"""In 100 words meditate on how future advancements on AI could affect your work practice as a communication designer."""

# AI offers us, the designers a whole bunch of new options to delve in with the process and understanding of designing. 
# It can help us to design something more time-efficient and more topic-related rather than with our sole knowledge and craftsmanship. 
# Advancements in AI will offer the designers a less required craftsmanship and lower skill-cap in any particular kind of designing. 
# Be it designing a poster with the aspects of futurism or designing a living room interior with the common understandment of Classical design.
# AI is fed with all the information. An information that none human can achieve to comprehend. 
# I would say it is a great tool of efficiency and utility for designing something that you do not have very good knowledge about. 
# But i cannot deny the fact that, it can make future designers works less 'hearted'. I mean that we may lose the grace of'human touch'in future designs by exploiting the power of AI design tools. 
# Thus, the act of designing can be all left randomised, full-machine operated 'process' without any human supervision in the future. 
# It fears me to think about it, sicne the design, should have a heart, and machines... They sure are stone-hearted fellows with no senses. Although, the question is can we alter that? Oh my...

"""Try to describe how you learn in algorithmic terms."""

# I am a 'homo-sapien' just like all my fellow society. We humans, learn by pictographic patternisations. Think about reading for example. Humans were not born with the innate capability of reading. 
# How do we read is that we had been taught the symbols, the letters that forms a meaningful word, a message to us. 
# And when it comes to learning with algorithmic terms just like a machine does, we are no different than them. We visualise an image in our mind and pattern it with its related attributes, thus forming an algorithm. 
# For example, when we see a cactus (considering that we know what is the attributes of cactuc, what it somewhat is.) we know that it is spiky and should not let it touch our skin: knowing that it may impale us.
# We had come to know that, the result is painful, something that we should avoid. This example is a definition of an algorithmic term. 
# Let us make it more computer rationalised: | 'Cactus: SPIKY, IMPOSES POSSIBLE DANGER FOR A HUMAN, OVERALL THREAT LEVEL SCALE: 1/10 , LEARNT DATA: DO NOT GET TOO CLOSE TO CACTUS OR ELSE, YOU WILL GET HURT' | 
# It is something like that, in a simplified way of telling.  Knowing what is something and correlating to its possible interactive results is what alogortihmic term in human learning is -- 
# also in machines but they do not fully depend on live action experiences, we can teach them directly! Or let them be taught by themselves, all thanks to our almighty creation of ML!

"""Create a python dictionary for your name surname and year of birth."""

a = {'name' : 'Agbey' , 'surname' : 'Demirdelen' , 'year_of_birth' : '1998'}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if a['name'][0] == 'a' :
   print('my initial letter is a')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len(a['surname']) % 3 == 0:
  print('it is divisible')
else: 
  print('not divisible')

"""Change your year of birth to 2678."""

a['year_of_birth'] = 2678

print(a)

"""Create a loop that goes through 20 to 40 and prints out the numbers that are divisble by 5."""

l = range(20,40)
for numbers in l:
    if numbers % 5 == 0:
      print(numbers)

"""Check the PDF on the Drive and calculate the neurons. Put all neurons and weights in python and do the calculation with them."""

print((0.87 * 0.12) + (0.87 * 0.06) + (0.87 * 0.06) + (0.87 * 0.76 ))



"""Using the code here:
https://github.com/anishathalye/neural-style
create a ***style transfer*** image.

Upload it along with this file.

You might need a file while doing this, it also is on the Drive!
"""
